# Generated by Django 4.0.2 on 2022-03-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propostions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.TextField()),
                ('theme', models.CharField(max_length=255)),
                ('sousTheme', models.CharField(max_length=255)),
                ('candidat', models.CharField(max_length=255)),
            ],
        ),
    ]
