# Generated by Django 4.0.2 on 2022-03-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propostions',
            new_name='Propositions',
        ),
        migrations.RenameField(
            model_name='propositions',
            old_name='sousTheme',
            new_name='section',
        ),
    ]
