# Generated by Django 4.0.2 on 2022-03-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_propostions_propositions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomPropositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.TextField()),
                ('theme', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('candidat', models.CharField(max_length=255)),
            ],
        ),
    ]
